module.exports ={
	INTEGER:          1<<0,
	REAL:             1<<1,
	CHAR:             1<<2,
	STRING:           1<<3,
	BOOLEAN:          1<<4,
	NULL:             1<<5,
	MATHFUNC:         1<<6,
	CONST:            1<<7,
	UNARY_LEFT_OP:    1<<8,
	UNARY_RIGHT_OP:   1<<9,
	BINARY_LOGIC_OP:  1<<10,
	BINARYOP:         1<<11,
	VAR:              1<<12,
	FUNC:             1<<13,
	PARENT:           1<<14,
	RESERVED:         1<<15,
	COMMA:            1<<16,
	ARGUMENT:         1<<17,
	PARAMETER:        1<<18,
	ASSIGN:           1<<19,
	NUMBER:           (1<<0 | 1<<1),
	ALL:              ((1<<20)-1)
};
